import {uploadPdf,getHealth,getDashboard,getAnomalies,getOutlook} from './api.js';import {renderDashboard,renderAnomalies} from './dashboard.js';import {loadPdf,navigate,zoom} from './pdf-viewer.js';import {initChat} from './chat.js';import {initReports} from './reports.js';
const $=id=>document.getElementById(id),state={documentId:null,pdfUrl:null,dashboard:null,openPdf:()=>show('pdf')};let pdfReady=false;
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function show(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(name+'View').classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name))}
function setupNav(){document.querySelectorAll('.nav,.text-btn').forEach(b=>b.onclick=()=>show(b.dataset.view));$('viewPdfBtn').onclick=()=>show('pdf');$('backFromPdf').onclick=()=>show('dashboard');}
function renderDocument(d){const a=d.analytics||{};$('documentWorkspace').innerHTML=`<div class="panel doc-profile"><div class="kicker">SOURCE DOCUMENT</div><div class="profile-title">${esc(d.filename)}</div>${[['Pages',a.pages],['Words',a.words],['Search chunks',a.chunks],['Detected tables',a.tables],['Characters',a.characters],['Evidence coverage',`${a.evidenceCoverage??'—'}%`]].map(x=>`<div class="profile-row"><span>${x[0]}</span><strong>${fmt(x[1])}</strong></div>`).join('')}</div><div class="panel"><div class="panel-head"><div><div class="kicker">TOP SECTIONS</div><h3>Document structure</h3></div></div><div class="section-tags">${(a.topSections||[]).map(x=>`<span class="section-tag">${esc(x)}</span>`).join('')||'<span class="muted">No section labels detected.</span>'}</div></div>`}
function renderTables(){const rows=state.dashboard?.analytics?.metrics||[], q=($('tableSearch').value||'').toLowerCase();const filtered=rows.filter(x=>`${x.name} ${x.category} ${x.sourcePage} ${x.unit}`.toLowerCase().includes(q));$('metricsTable').innerHTML=filtered.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.value)}</td><td>${esc(x.unit||'')}</td><td>${esc(x.category)}</td><td><button class="citation" onclick="window.__openPage(${x.sourcePage})">Page ${x.sourcePage}</button></td><td>${Math.round((x.confidence||0)*100)}%</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No structured metrics detected in this document.</td></tr>';$('tableCount').textContent=`${filtered.length} records`}
function renderSpecialViews(){const a=state.dashboard?.analytics||{};$('analyticsGrid').innerHTML=[['Production metrics',(a.metrics||[]).filter(x=>x.category==='operations')],['Quality metrics',(a.metrics||[]).filter(x=>x.category==='quality')]].map(([title,arr])=>`<article class="panel analytics-card"><div class="kicker">SOURCE-DERIVED</div><h3>${title}</h3><div>${arr.length?arr.slice(0,8).map(x=>`<div class="profile-row"><span>${esc(x.name)} · p.${x.sourcePage}</span><strong>${fmt(x.value)} ${esc(x.unit||'')}</strong></div>`).join(''):'<span class="muted">No relevant structured values detected.</span>'}</div>`).join('');$('geologyGrid').innerHTML=[['Exploration metrics',(a.metrics||[]).filter(x=>x.category==='exploration')],['Resources & reserves',(a.metrics||[]).filter(x=>x.category==='resources')]].map(([title,arr])=>`<article class="panel analytics-card"><div class="kicker">SOURCE-DERIVED</div><h3>${title}</h3>${arr.length?arr.map(x=>`<div class="profile-row"><span>${esc(x.name)} · p.${x.sourcePage}</span><strong>${fmt(x.value)} ${esc(x.unit||'')}</strong></div>`).join(''):'<p>No relevant structured values detected in this document.</p>'}</article>`).join('');const series=a.series||[];$('trendCards').innerHTML=series.length?series.map(s=>`<article class="panel analytics-card"><div class="kicker">${esc(s.unit||'TIME SERIES')}</div><h3>Historical evidence</h3>${s.values.map(v=>`<div class="profile-row"><span>${v.year} · page ${v.sourcePage}</span><strong>${fmt(v.value)}</strong></div>`).join('')}</article>`).join(''):'<div class="panel analytics-card"><h3>No historical series</h3><p>At least three year/value observations are required for this view.</p></div>'}
async function loadDoc(d){state.documentId=d.id;state.pdfUrl=`http://localhost:4000${d.fileUrl}`;$('activeDoc').textContent=d.filename;$('pdfName').textContent=d.filename;$('ask').disabled=false;$('viewPdfBtn').disabled=false;$('indexStatus').textContent='● Indexed & evidence-ready';state.dashboard=await getDashboard(d.id);renderDashboard(state.dashboard);renderDocument(state.dashboard.document);renderTables();renderSpecialViews();const an=(await getAnomalies(d.id)).anomalies;renderAnomalies(an);$('riskCards').innerHTML=an.length?an.map(x=>`<article class="panel risk-card"><span class="severity ${x.severity}">${x.severity}</span><b>${esc(x.title)}</b><p>${esc(x.description)}</p><small class="muted">Pages ${(x.sourcePages||[]).join(', ')}</small></article>`).join(''):'<article class="panel risk-card"><b>No material anomalies detected</b><p>The available structured evidence did not produce a significant anomaly.</p></article>';const out=(await getOutlook(d.id)).outlook;$('outlookCard').innerHTML=out.available?`<div class="kicker">AI-ASSISTED PROJECTION</div><div class="outlook-title">${esc(out.label)}</div><p class="muted">Projection uses a simple linear trend over the latest documented historical values. It is not a guaranteed prediction.</p><div class="projection">${out.historical.slice(-2).map(x=>`<div><span>Historical ${x.year}</span><b>${fmt(x.value)}</b></div>`).join('')}${out.projections.map(x=>`<div><span>Projected ${x.year}</span><b>${fmt(Math.round(x.value))}</b></div>`).join('')}</div><p class="muted">Confidence signal: ${out.confidence}% · evidence pages ${out.evidencePages.join(', ')}</p>`:'<div class="empty"><div><b>Insufficient historical data for projection.</b><br><span>At least four source observations are required.</span></div></div>';toast('Document indexed successfully')}
$('uploadBtn').onclick=$('emptyUpload').onclick=()=>$('pdfInput').click();$('pdfInput').onchange=async()=>{const f=$('pdfInput').files[0];if(!f)return;$('indexStatus').textContent='● Processing PDF…';toast('Uploading and indexing…');try{const d=await uploadPdf(f);await loadDoc(d.document);await openPdf()}catch(e){toast(e.message);$('indexStatus').textContent='● Processing failed'}};
async function openPdf(){show('pdf');if(!pdfReady){await loadPdf(state.pdfUrl,$('pdfViewer'));pdfReady=true}}
$('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);$('minus').onclick=()=>zoom(-.15);$('plus').onclick=()=>zoom(.15);$('tableSearch').oninput=renderTables;window.__openPage=async p=>{await openPdf();const {scrollToPage}=await import('./pdf-viewer.js');scrollToPage(p)};
$('globalSearch').oninput=e=>{if(e.target.value.trim())show('explorer')};setupNav();initChat(state,toast);initReports(state,toast);getHealth().then(()=>{['mongoStatus','ragStatus','aiStatus'].forEach(id=>$(id).textContent='Online')}).catch(()=>{['mongoStatus','ragStatus','aiStatus'].forEach(id=>$(id).textContent='Check config')});
function fmt(n){return n===undefined||n===null?'N/A':typeof n==='number'?n.toLocaleString():String(n)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
