let chart;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>typeof n==='number'?n.toLocaleString():String(n??'—');
export function renderDashboard(data){const a=data.analytics||{},m=a.metrics||[],series=a.series||[];document.getElementById('emptyDashboard').classList.add('hidden');document.getElementById('dashboardBody').classList.remove('hidden');document.getElementById('dashboardSubtitle').textContent=`${data.document.filename} · ${a.pages||0} pages · evidence-linked workspace`;
const cards=[['Pages',a.pages,'Document length'],['Words',a.words,'Extracted text'],['Search chunks',a.chunks,'Semantic units'],['Tables',a.tables,'Detected tables'],['Metrics',m.length,'Source-derived values'],['Evidence',`${a.evidenceCoverage??'—'}%`,'Coverage signal']];document.getElementById('kpis').innerHTML=cards.map(x=>`<article class="panel kpi"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${fmt(x[1])}</div><div class="kpi-meta">${x[2]}</div></article>`).join('');
const list=document.getElementById('metricList');list.innerHTML=m.length?m.slice(0,14).map(x=>`<div class="metric-row"><div><span>${esc(x.name)}</span><small>Page ${x.sourcePage} · ${Math.round((x.confidence||0)*100)}% extraction confidence</small></div><b>${fmt(x.value)} ${esc(x.unit||'')}</b></div>`).join(''):'<div class="empty">No structured metrics detected in this document.</div>';
if(chart)chart.destroy();const ctx=document.getElementById('trendChart').getContext('2d');if(series.length){document.getElementById('trendEmpty').classList.add('hidden');const s=series[0];chart=new Chart(ctx,{type:'line',data:{labels:s.values.map(x=>x.year),datasets:[{label:s.unit||'Documented metric',data:s.values.map(x=>x.value),tension:.25,borderWidth:2,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#8aa39a',font:{size:9}}}},scales:{x:{ticks:{color:'#617a71',font:{size:8}},grid:{color:'#163028'}},y:{ticks:{color:'#617a71',font:{size:8}},grid:{color:'#163028'}}}}})}else document.getElementById('trendEmpty').classList.remove('hidden');
renderInsights(data.insights||[]);}
export function renderInsights(items){document.getElementById('insights').innerHTML=items.length?items.map(i=>`<div class="insight"><span class="tag">${esc(i.category)}</span><span class="severity ${i.severity||'INFO'}">${esc(i.severity||'INFO')}</span><b>${esc(i.title)}</b><p>${esc(i.description)} · ${esc(i.metric||'')}</p><small class="muted">Pages ${(i.sourcePages||[]).join(', ')}</small></div>`).join(''):'<div class="empty">No evidence-backed decision insights detected.</div>'}
export function renderAnomalies(items){document.getElementById('anomalies').innerHTML=items.length?items.slice(0,5).map(i=>`<div class="risk"><span class="severity ${i.severity}">${i.severity}</span><b>${esc(i.title)}</b><p>${esc(i.description)}</p><small class="muted">Pages ${(i.sourcePages||[]).join(', ')}</small></div>`).join(''):'<div class="empty">No material anomalies detected from available structured evidence.</div>'}
