import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';
let pdfDoc=null,scale=1.15,pages=[],container=null;
export async function loadPdf(url,target){container=target;container.dataset.pdfUrl=url;container.innerHTML='<div class="empty">Rendering source document…</div>';pdfDoc=await pdfjsLib.getDocument(url).promise;container.innerHTML='';pages=[];const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)renderPage(Number(e.target.dataset.page))}),{root:container,rootMargin:'500px'});for(let n=1;n<=pdfDoc.numPages;n++){const wrap=document.createElement('div');wrap.className='pdf-page';wrap.dataset.page=n;wrap.style.minHeight='120px';container.appendChild(wrap);pages.push({num:n,wrap});observer.observe(wrap)}document.getElementById('pageInfo').textContent=`1 / ${pdfDoc.numPages}`;return pdfDoc.numPages}
async function renderPage(n){const item=pages.find(x=>x.num===n);if(!item||item.rendered)return;item.rendered=true;const page=await pdfDoc.getPage(n),viewport=page.getViewport({scale});item.viewport=viewport;item.wrap.style.width=`${viewport.width}px`;item.wrap.style.minHeight=`${viewport.height}px`;const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;item.wrap.innerHTML='';item.wrap.appendChild(canvas);const overlay=document.createElement('div');overlay.className='overlay';Object.assign(overlay.style,{width:`${viewport.width}px`,height:`${viewport.height}px`});item.wrap.appendChild(overlay);item.overlay=overlay}
export function zoom(delta){scale=Math.min(2.3,Math.max(.7,scale+delta));if(!container?.dataset.pdfUrl)return;loadPdf(container.dataset.pdfUrl,container)}
export function scrollToPage(page){const item=pages.find(x=>x.num===Number(page));if(item){item.wrap.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('pageInfo').textContent=`${item.num} / ${pdfDoc.numPages}`}}
export function highlightCitation(c){const item=pages.find(x=>x.num===Number(c.page));if(!item)return;renderPage(item.num).then(()=>{document.querySelectorAll('.highlight').forEach(x=>x.remove());if(!c.bbox)return;const r=item.viewport.convertToViewportRectangle([c.bbox.x0,c.bbox.y0,c.bbox.x1,c.bbox.y1]);const box=document.createElement('div');box.className='highlight';Object.assign(box.style,{left:`${Math.min(r[0],r[2])}px`,top:`${Math.min(r[1],r[3])}px`,width:`${Math.abs(r[2]-r[0])}px`,height:`${Math.abs(r[3]-r[1])}px`});item.overlay.appendChild(box);scrollToPage(c.page)})}
export function navigate(delta){const current=Number((document.getElementById('pageInfo').textContent||'1').split('/')[0]);scrollToPage(Math.max(1,Math.min(pdfDoc?.numPages||1,current+delta)))}
